### PR TITLE
Make a release on PyPI via github actions

### PR DESCRIPTION
**Pull request by lopuhin**
TODO: set up secrets.

### CODE REVIEW

**Comment by lopuhin** [comment]
@kmike do you know if we have pypi credentials set up in the org via github secrets (https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets), or do we do that per repo? Do we release via GH actions in any other repos?

**Comment by Gallaecio** [comment]
cc @elacuesta (https://github.com/scrapy/scrapy/pull/4924)

**Comment by kmike** [comment]
@lopuhin I think we do it per-repo. I don't have pypi access to extruct - it seems we should ask our infra team to add a secret.

**Comment by lopuhin** [comment]
Now secrets are set up (thanks!), I'll merge it and will try making a release.

**Comment by lopuhin** [comment]
Actions were triggered correctly (https://github.com/scrapinghub/extruct/runs/1617806653?check_suite_focus=true) but they didn't succeed due to

```
The description failed to render for 'text/x-rst'. See https://pypi.org/help/#description-content-type for more information.
``` 

which is likely due to #162 and not related to this PR. I removed the tag, will try to fix this and try again.

**Comment by lopuhin** [comment]
it's released now at https://pypi.org/project/extruct/0.12.0/ with a shiny new description thanks to @jayaddison

**Pull request merged**
