### PR TITLE
add six to requirements

### PR DESCRIPTION
**Pull request by pawelmhm**
this fixes broken build

### CODE REVIEW

**Comment by redapple** [comment]
@pawelmhm , you mean the [build for tmp-rdfa branch](https://travis-ci.org/scrapinghub/extruct/builds/135593653)?
`six` is not used on master branch

**Comment by pawelmhm** [comment]
> you mean the build for tmp-rdfa branch?

ah sorry, I thought this is master failing. This icon in repo (see screenshot) seems to change colors on branch builds, it is now green after branch build passed, but was red earlier. Shouldn't it change color only on master builds? You can try creating failed build on branch and see how icon changes.

icon

I installed extruct to my project today saw red in master repo and fixed that. If all is well and good I'll close this PR.

**Comment by redapple** [comment]
Thanks for the noticing. You are correct that the icon was red, but it was for that temp branch that I shared for @carlosp420, and which is really really not tested.
I'll update the build icon to use master branch.

**Comment by pawelmhm** [comment]
no problem it's a matter of switching

```
-.. image:: https://img.shields.io/travis/scrapinghub/extruct.svg
to:
+.. image:: https://img.shields.io/travis/scrapinghub/extruct/master.svg
```

**Pull request closed without merging**
