### PR TITLE
Add support for embedded JSON-LD

### PR DESCRIPTION
**Pull request by redapple**

### CODE REVIEW

**Comment by redapple** [comment]
@eliasdorneles ,
what do you think?

**Comment by eliasdorneles** [comment]
Hey @redapple, nice feature, looks good!

One thing I noticed is that `extract_items` here returns a list of items (which seems fine) but the microdata extractor returns a dict with an `items` key, which seems a bit inconsistent.

Is this the expected behavior?
Wouldn't it make sense to change the microdata extractor to return a list too?

Keeping the same interface across extractors would probably make it easier for the service (which could be updated to use this one too, maybe in a separated PR).

**Comment by redapple** [comment]
Indeed,
`w3cmicrodata` follow http://www.w3.org/TR/microdata/#json, which defines the results as an array containing an `items` field.
For JSON-LD, I haven't found the equivalent guidelines for the result format.
But it does make sense to return lists in all cases.

**Comment by redapple** [comment]
I used `{"items": ...}` as well, to leave room for additional metadata

**Comment by eliasdorneles** [comment]
LGTM! :+1:

**Pull request merged**
