### PR TITLE
0.9.0 release

### PR DESCRIPTION
**Pull request by lopuhin**
As I understand, we release to pypi automatically on git tags - I plan to tag after merging this PR into master.

### CODE REVIEW

**Comment by kmike** [comment]
hey! I think we've done it is 

1) merge a PR with changelog (with a version already in)
2) update all versions everywhere & add a git tag, by running `bumpversion minor --dry-run --verbose` (to check if everything is ok) and then `bumpversion minor` and then pushing everything to git, including tags

**Comment by kmike** [comment]
bumpversion command should add a proper git tag & update version numbers in all necessary places

**Comment by lopuhin** [comment]
Thanks @kmike I reverted the version change, will update the docs on how to make a release once I make it

**Comment by kmike** [comment]
thanks @lopuhin!

**Comment by kmike** [comment]
Feel free to push the version change to master

**Pull request merged**
