### PR TITLE
Document how to make releases

### PR DESCRIPTION
**Pull request by lopuhin**
TODO:

- [x] try to follow this for 0.10.0 release

### CODE REVIEW

**Comment by lopuhin** [comment]
Sorry for the mess with multiple tried to make a release in master, original sequence didn't work and then I didn't notice that upload already succeeded on the next try. Documented the working sequence, hope it goes smoother next time.

**Comment by kmike** [comment]
Thanks @lopuhin! 
The sequence makes sense to me, especially as you checked that it works :)

Do you think we can move it to wiki? 
This is information for maintainers, not for general extruct users.

**Comment by lopuhin** [comment]
> Do you think we can move it to wiki? This is information for maintainers, not for general extruct users.

@kmike good point, I can move it along with bumpversion mention. Another option besides the wiki is to have it in git, e.g. in ``RELEASE.rst`` or ``MAINTENANCE.rst`` for easier discoverability, what do you think?

**Comment by kmike** [comment]
I think both are fine, not strong preference. I've seen @Gallaecio updating release procedure in wiki almost on each release sometimes, when it's complex, but here it looks pretty straightforward.

**Comment by lopuhin** [comment]
Aha I didn't know we already use wiki for that purpose, nice, make sense to follow the same approach here.

**Comment by kmike** [comment]
We're not using it for this repo, but we have release procedure in wiki for Scrapy, Splash and some other Open Source packages we maintain - see e.g. https://github.com/scrapy/scrapy/wiki/Scrapy-release-procedure or https://github.com/scrapinghub/splash/wiki/How-to-make-a-Splash-release.

**Comment by lopuhin** [comment]
Thanks for context @kmike , makes sense to use a similar approach across our repos. Created a wiki page https://github.com/scrapinghub/extruct/wiki and removed stuff from the README.

**Comment by kmike** [comment]
Thanks @lopuhin for taking care of that!

**Comment by lopuhin** [comment]
thanks @kmike !

**Pull request merged**
